ALTER TABLE time_block ADD COLUMN actual_start TIMESTAMP WITH TIME ZONE;
ALTER TABLE time_block ADD COLUMN actual_end   TIMESTAMP WITH TIME ZONE;
ALTER TABLE time_block ADD COLUMN was_completed BOOLEAN NOT NULL DEFAULT false;
